[package]
name = "dieseltest"
version = "0.1.0"
authors = ["Kamek <b.kamek@gmail.com>"]

[dependencies]
diesel = { version = "1.3.0", features = ["postgres"] }
shared-types = { path = "../shared-types" }
